[build]
builder = "nixpacks"

[deploy]
startCommand = "cd /app/build && npx serve -s -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_OPTIONS = "--max-old-space-size=512"
