[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npm run serve"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
PORT = "3000"
NODE_OPTIONS = "--max-old-space-size=512"