[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npx serve -s build -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_OPTIONS = "--max-old-space-size=512"
REACT_APP_API_URL = "https://projeto-valex.railway.internal/api"
