[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npx serve -s build -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 3
