[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npx serve -s build -l $PORT --single"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
NODE_OPTIONS = "--max-old-space-size=512"
REACT_APP_API_URL = "https://projeto-valex.railway.internal/api"
