[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npx serve -s build -l 3.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
PORT = "3000"
NODE_OPTIONS = "--max-old-space-size=512"
REACT_APP_API_URL = "https://projeto-valex.railway.internal/api"