services:
  - type: web
    name: valex-api
    env: python
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn wsgi:app"
    rootDir: backend
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: valex-db
          property: connectionString

  - type: web
    name: valex-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://valex-api.onrender.com

databases:
  - name: valex-db
    databaseName: valex
    user: valex