[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 3