[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:create_app()"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.healthcheck]
interval = "15s"
timeout = "5s"
retries = 3