[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python start.py"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300


[deploy.healthcheck]
interval = "15s"
timeout = "5s"
retries = 3