[build]
builder = "nixpacks"
buildCommand = """
cd frontend && npm install && npm run build && cd .. && 
pip install -r requirements.txt
"""

[deploy]
  startCommand = "python3 start.py"
  restartPolicyType = "ON_FAILURE"
  healthcheckPath = "/"
  healthcheckTimeout = 300