[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 3